package io.schemat.connector.core.crypto

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.security.KeyPairGenerator
import java.security.Signature
import java.util.Base64

class Ed25519Test {

    // Golden vector generated by PHP libsodium (sodium_crypto_sign_detached) with the
    // fixed 32x0x42 seed — the exact cross-repo contract (plan §C3). If this test fails,
    // schemati and the connector have diverged on the signing contract.
    private val publicKey = Base64.getDecoder().decode("IVL40Zt5HSRFMkLhXy6rbLfP+ntqXtMAl5YOBpiB2xI=")
    private val payload =
        """{"communityId":"11111111-2222-3333-4444-555555555555","issuedAt":1760000000,"nonce":"000102030405060708090a0b0c0d0e0f","platform":"PAPER_PLUGIN","tokenId":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"}"""
    private val signature = Base64.getDecoder().decode(
        "WgS1p0Ug618bFMzOPVGYanT9ZwKUe8eRPStRN9KxTRSWqbCJc0vLs3SJcws6qsR8V69P8v/s+p6Xe1rpXgaJCw==",
    )

    @Test
    fun `verifies the PHP-signed golden vector`() {
        assertTrue(Ed25519.verify(publicKey, payload.toByteArray(Charsets.UTF_8), signature))
    }

    @Test
    fun `rejects a tampered payload`() {
        val tampered = payload.replace("PAPER_PLUGIN", "FABRIC_SERVER")
        assertFalse(Ed25519.verify(publicKey, tampered.toByteArray(Charsets.UTF_8), signature))
    }

    @Test
    fun `rejects a tampered signature`() {
        val bad = signature.copyOf().also { it[0] = (it[0].toInt() xor 1).toByte() }
        assertFalse(Ed25519.verify(publicKey, payload.toByteArray(Charsets.UTF_8), bad))
    }

    @Test
    fun `rejects the wrong key and malformed inputs`() {
        assertFalse(Ed25519.verify(ByteArray(32), payload.toByteArray(Charsets.UTF_8), signature))
        assertFalse(Ed25519.verify(ByteArray(31), payload.toByteArray(Charsets.UTF_8), signature)) // wrong key length
        assertFalse(Ed25519.verify(publicKey, payload.toByteArray(Charsets.UTF_8), ByteArray(63))) // wrong sig length
    }

    @Test
    fun `round-trips against a JVM-generated keypair`() {
        val keyPair = KeyPairGenerator.getInstance("Ed25519").generateKeyPair()
        val message = "handshake-v2".toByteArray(Charsets.UTF_8)
        val sig = Signature.getInstance("Ed25519").run {
            initSign(keyPair.private)
            update(message)
            sign()
        }
        // X.509 SubjectPublicKeyInfo for Ed25519 is a fixed 12-byte prefix + 32 raw bytes.
        val raw = keyPair.public.encoded.copyOfRange(keyPair.public.encoded.size - 32, keyPair.public.encoded.size)
        assertTrue(Ed25519.verify(raw, message, sig))
        assertFalse(Ed25519.verify(raw, "other".toByteArray(Charsets.UTF_8), sig))
    }
}
